### ISSUE TITLE
New login screen backgound image

### ISSUE THREAD

**Issue by shalzz** [shalzz/college-academics#1]
Design a new cool and abstract background image for the login screen.

**Comment by hemangsk** [comment]
Hey @Shalzz !😄 FOA great app. 🎉 
 I'd like work on this enhancement...

**Comment by hemangsk** [comment]
![android l](https://cloud.githubusercontent.com/assets/13018570/19013338/6cff3558-87eb-11e6-9e35-a9e5faf993c1.png)
![android l2](https://cloud.githubusercontent.com/assets/13018570/19013339/6eeaa9e2-87eb-11e6-94b0-02c43d5a00f8.png)

Thoughts?

**Comment by shalzz** [comment]
Wow! looks amazing!
Please go ahead and send me a pull request whenever you're ready.

**Comment by hemangsk** [comment]
On it! 👍

**Comment by shalzz** [comment]
Hey @hemangsk just wanted to give you a heads up, please do all development on the dev branch and send a pull request to the dev branch only.
Also if you are doing something other than just adding the background image please do it on a separate commit/pull request (by creating a separate branch on your repo for every pull request).
Thanks.

**Comment by hemangsk** [comment]
Thanks a lot for the directions 👍  😄

**Comment by hemangsk** [comment]
Sent PR #9  ..creating new PR to correct the font colors so that they become visible on new background 😄

**Comment by hemangsk** [comment]
Attaching an in-progress screenshot of login screen, actually I needed your thoughts on this ->
since a new user register functionality is not required in the app, I was thinking if we can pull out the floating button from the login box? 💭 

![screenshot_20161002-211020](https://cloud.githubusercontent.com/assets/13018570/19021717/46e728b2-88e5-11e6-97d1-cde60bc103c5.png)

**Comment by shalzz** [comment]
Looks great, though you could lose the UPES academics title and yeah the fab is not required.

**Comment by shalzz** [comment]
@hemangsk are you still working on this?

**Comment by hemangsk** [comment]
Yep.. I was just learning about fetching new changes from upstream so that I can send you PR, wont take much time an hr at max

**Comment by hemangsk** [comment]
Matched the colours on login screen with the app's colour scheme, and removed UPES ACADEMICS title from top. 

![screenshot_20161004-195230](https://cloud.githubusercontent.com/assets/13018570/19078037/67038770-8a6c-11e6-9b71-d1f76b3c4595.png)

**Comment by shalzz** [comment]
Great, the "LOGIN" is also quite redundant plus you could reduce the space between the two fields to show more of the image.
Just do a git pull --rebase

**Comment by hemangsk** [comment]
After removing redundancy and extra spaces 😃   👍 

![screenshot_20161004-204255](https://cloud.githubusercontent.com/assets/13018570/19080003/403e6a18-8a73-11e6-892e-d3ed8732f1b6.png)

**Comment by shalzz** [comment]
Hey @hemangsk the image you added is really low resolution.
Can you add the image with the following sizes:
xxxhdpi: 1280x1920 px
xxhdpi: 960x1600 px
xhdpi: 640x960 px
hdpi: 480x800 px
mdpi: 320x480 px
ldpi: 240x320 px

Thanks

**Comment by hemangsk** [comment]
OK gotcha 👍on it :smiley:

**Comment by hemangsk** [comment]
Solved in #12 😄
