### ISSUE TITLE
Fix incorrect Fragment position

### ISSUE THREAD

**Issue by shalzz** [shalzz/college-academics#3]
At https://github.com/Shalzz/upes-academics/blob/dev/attendance/src/main/java/com/shalzz/attendance/ui/timetable/TimeTablePagerAdapter.java#L64
when reassigning fragments a new position based on their date, the fragments are not really assigned the correct position when using the jump to date feature.

**Comment by akm0012** [comment]
Do you have some dummy credentials I can use to "log in"?  Trying to get to the screen with this Adapter.

**Comment by shalzz** [comment]
Sure you can use:
Sap id: 500029490
password: password

**Comment by akm0012** [comment]
So is the issue that "Scroll to date" menu option isn't implemented? It looks like the dialog isn't being shown.  Trying figure out if this is a bug or more of a feature request. 

Also, I'd recommend looking into JodaTime. May make a lot of your time logic easier.

**Comment by shalzz** [comment]
No, sorry the menu option not working was a regression, I just pushed a commit that fixes it.
Please take a look again.

**Comment by akm0012** [comment]
Gotcha, so everything looks like it is working. Is the issue that the fragment being scrolled to really isn't the fragment / class schedule for that date?

**Comment by shalzz** [comment]
Yes, exactly. The schedule of a day is the same for any week. For eg 30 september's schedule is the same for 23 sept (both are friday).

**Comment by akm0012** [comment]
I'd look at your `positions` HashMap. It has a lot of duplicate position values and finding dates 20+ years from now.
